services:
  fontzy:
    build: .
    container_name: fontzy
    ports:
      - "6000:8000"
    volumes:
      - ./fonts:/app/fonts
    environment:
      - FONTZY_INCOMING_DIR=/app/fonts/incoming
      - FONTZY_SERVED_DIR=/app/fonts/served
      - FONTZY_METADATA_FILE=/app/fonts/font-metadata.json
      - FONTZY_SETTINGS_FILE=/app/fonts/fontzy-settings.json
    restart: unless-stopped
